### PR TITLE
Fix #123, `UseNumber` not works with iterator

### LINKED ISSUE #123: Iterator.Read should return json.Number when use number
currently it always return float64, should be fixed

### PR DESCRIPTION
**Pull request by carlcarl**

### CODE REVIEW

File: feature_iter.go [hunk 1]
```diff
@@ -273,6 +273,9 @@ func (iter *Iterator) Read() interface{} {
 	case String:
 		return iter.ReadString()
 	case Number:
+		if iter.cfg.configBeforeFrozen.UseNumber {
+			return iter.ReadInt()
```
Comment (taowen) [inline feature_iter.go]: this is wrong. UseNumber should return json.Number (which is string)

Comment (carlcarl) [inline feature_iter.go]: OK

**Comment by taowen** [comment]
thanks!
