### PR TITLE
jsoniter: Fix errors during reading integers from chunked io.Reader

### LINKED ISSUE #476: assertInteger: can not decode float as int for valid input from chunked reader
Hi,
we found a bug during unmarshaling large responses from [HTTP.Request.Body](https://pkg.go.dev/net/http?tab=doc#Request.Body). The next conditions should be met:
- Iterator reads data from `io.Reader`,
- expected value is `0` (zero)
- `Iterator.tail == Iterator.head + 1`
- `Iterator.tail < len(Iterator.buf)`
- value in the buffer after `Iterator.tail` is presented from the previous read and has '.' character.

Basically, let's assume that `Iterator` reads data from the reader which returns less data, than the size of the buffer. After a couple of reads, the buffer will have the content like: `0.0, 0.0, 0`.
The first item is from the latest read, other items are from the older readers, so have:
```go
buf: []bytes(`0.0, 0.0, 0`)
head: 0 // ---^
tail: 1 // ----^
```

When the `Iterator.ReadInt` is called, it [reads zero and checks if the value is an integer](https://github.com/json-iterator/go/blob/ebe943a/iter_int.go#L123-L126) by calling  [`assertInteger()` method](https://github.com/json-iterator/go/blob/ebe943a/iter_int.go#L341-L345), which currently looks like:
```go
func (iter *Iterator) assertInteger() {
	if iter.head < len(iter.buf) && iter.buf[iter.head] == '.' {
		iter.ReportError("assertInteger", "can not decode float as int")
	}
}
```

The only issue is, that it checks for `iter.head < len(iter.buf)` instead of `iter.head < iter.tail` and the assertion is done against the dot `.` from the previous read.

The test for replicating this behavior will be provided in ongoing PR.

### PR DESCRIPTION
**Pull request by mrVanboy**
This commit fixes bug in Iterator.assertInteger method if the next
conditions are met:
- Iterator reads data from `io.Reader`,
- expected value is `0` (zero)
- `Iterator.tail == Iterator.head + 1`
- `Iterator.tail < len(Iterator.buf)`
- value in the buffer after `Iterator.tail` is presented from the previous read and has '.' character.

Typical error which user cal see is:
- assertInteger: can not decode float as int, error found in #X byte of ...

Regression test added for checking the correct behaviour.

Fixes #476

### CODE REVIEW

**Comment by AllenX2018** [comment]
Thanks for the bug report and the pr. I will check it in the next few days.

**Comment by mrVanboy** [comment]
@AllenX2018 any updates plz 🙏 ? We already using our fork with the current PR branch for a couple of weeks in production and we haven't noticed any issues.

File: iter_int_test.go [hunk 1]
```diff
@@ -0,0 +1,101 @@
+package jsoniter_test
```
Comment (AllenX2018) [inline iter_int_test.go:1]: Could you move this test case to the *jsoniter_int_test.go* under misc_tests directory?

**Comment by AllenX2018** [comment]
Hi! Sorry for the late reply. I leave a review comment and please check it.

File: iter_int_test.go (hunk 1 above)
Comment (mrVanboy) [reply iter_int_test.go]: Done. Wasn't sure originally where to place this test 🤷

**Comment by AllenX2018** [comment]
Merged. Thanks!
